# cargo配置文件
# [package]是一个片段（section）标题，表明下面的语句用来配置一个包。
# 随着我们在这个文件增加更多的信息，还将增加其他片段（section）
[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["chris"]
# [dependencies]是罗列项目依赖的片段。
# 在Rust中，代码包被称为crates。
[dependencies]
